### ISSUE TITLE
Please consider adding an explicit License file

### ISSUE THREAD

**Issue by arfon** [pyk/sublime-terra#1]
Hello there, we'd like to use this grammar on https://github.com/github/linguist but are unable to because the license isn't explicitly stated. I realise you already have `BSD 3-Clause` stated in the README but would you mind also adding a LICENSE file with the actual BSD 3-Clause license?

/ cc https://github.com/github/linguist/pull/2875

**Comment by arfon** [comment]
/ cc @pyk

**Comment by pyk** [comment]
@arfon done! https://github.com/pyk/sublime-terra/commit/d77b0341d26f0989b2dc918ce9fb5cb8a5c7202b :+1:

**Comment by arfon** [comment]
@pyk many thanks!
